module.exports.descriptors = [
    'Chewy',
    'Booby',
    'Cookie',
    'Whoo',
    'Stinky',
    'Sweet',
    'Pretty',
    'Ugly',
    'Big',
    'Slimey',
    'Itchy',
    'Large',
    'Small',
    'Hideous',
    'Brown',
    'White',
    'Orange',
    'Black',
]
module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
]